/**
 * Migration script to create Open Stock items in Sanity
 *
 * Run with:
 * NEXT_PUBLIC_SANITY_PROJECT_ID=xxx NEXT_PUBLIC_SANITY_DATASET=production SANITY_API_TOKEN=xxx npx tsx scripts/create-open-stock.ts
 */

import { createClient } from "@sanity/client"

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET || "production"
const token = process.env.SANITY_API_TOKEN

if (!projectId || !token) {
  console.error("Missing environment variables. Please set:")
  console.error("  NEXT_PUBLIC_SANITY_PROJECT_ID")
  console.error("  NEXT_PUBLIC_SANITY_DATASET (optional, defaults to production)")
  console.error("  SANITY_API_TOKEN")
  process.exit(1)
}

const client = createClient({
  projectId,
  dataset,
  token,
  apiVersion: "2024-01-01",
  useCdn: false,
})

// Open Stock data from CSV
const openStockData = [
  {
    fabric: "Brushed Cotton",
    colorway: "Grey",
    itemNumber: "720003-01",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Pale Blue",
    itemNumber: "720003-02",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Grey/Blue",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Sky",
    itemNumber: "720003-03",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Blue",
    itemNumber: "720003-04",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Blue Grey",
    itemNumber: "720003-05",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Cobalt",
    itemNumber: "720003-06",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Royal",
    itemNumber: "720003-07",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Denim",
    itemNumber: "720003-08",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Blue/Navy",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Indigo",
    itemNumber: "720003-09",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Blue/Navy",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Teal",
    itemNumber: "720003-10",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Blue/Green",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Scarlet",
    itemNumber: "720003-11",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Red",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Wine",
    itemNumber: "720003-12",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Red",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Chalk",
    itemNumber: "720003-13",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Off White",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Aluminum",
    itemNumber: "720003-14",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Graphite",
    itemNumber: "720003-15",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Coffee",
    itemNumber: "720003-16",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Cappuccino",
    itemNumber: "720003-17",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Sandstone",
    itemNumber: "720003-18",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Brown/Beige/Natural",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Navy",
    itemNumber: "720003-19",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Blue/Navy",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Clove",
    itemNumber: "720003-20",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Green/Beige",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Dune",
    itemNumber: "720003-21",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Tan/Natural",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Sand",
    itemNumber: "720003-22",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Beige/Natural",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Ivory",
    itemNumber: "720003-23",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Beige",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Eggshell",
    itemNumber: "720003-24",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Off White",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "White",
    itemNumber: "720003-25",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "White",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Powder",
    itemNumber: "720003-26",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Off White",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Smoke",
    itemNumber: "720003-27",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Grey/Natural",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Stone",
    itemNumber: "720003-28",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Elephant",
    itemNumber: "720003-29",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Breeze",
    itemNumber: "720003-30",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Jade",
    itemNumber: "720003-31",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Parsley",
    itemNumber: "720003-32",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Wasabi",
    itemNumber: "720003-33",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Celery",
    itemNumber: "720003-34",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Green/Gold",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Lettuce",
    itemNumber: "720003-35",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Ochre",
    itemNumber: "720003-36",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Gold/Yellow",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Acorn",
    itemNumber: "720003-37",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Toast",
    itemNumber: "720003-38",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Pumpkin",
    itemNumber: "720003-39",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Orange",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Coral",
    itemNumber: "720003-40",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Red/Pink",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Chili",
    itemNumber: "720003-41",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Red/Orange",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Tomato",
    itemNumber: "720003-42",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Red",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Beet",
    itemNumber: "720003-43",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Red/Pink",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Magenta",
    itemNumber: "720003-44",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Pink",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Orchid",
    itemNumber: "720003-45",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Pink/Purple",
  },
  {
    fabric: "Brushed Cotton",
    colorway: "Pink",
    itemNumber: "720003-46",
    price: 68,
    content: "100% Cotton",
    width: '55"',
    description: "Solid",
    color: "Pink",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "White",
    itemNumber: "720002-01",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "White",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Cream",
    itemNumber: "720002-02",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Off White",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Café au Lait",
    itemNumber: "720002-03",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Natural/Cream",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Cloud",
    itemNumber: "720002-04",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Off White",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Fog",
    itemNumber: "720002-05",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Natural",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Pearl",
    itemNumber: "720002-06",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Slate",
    itemNumber: "720002-07",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Graphite",
    itemNumber: "720002-08",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Umber",
    itemNumber: "720002-09",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Grey/Brown",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Espresso",
    itemNumber: "720002-10",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Plum",
    itemNumber: "720002-11",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Purple",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Tobacco",
    itemNumber: "720002-12",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Brown/Tan",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Mauve",
    itemNumber: "720002-13",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Purple",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Sky",
    itemNumber: "720002-14",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Gray Blue",
    itemNumber: "720002-15",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Aegean",
    itemNumber: "720002-16",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Ultramarine",
    itemNumber: "720002-17",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Navy",
    itemNumber: "720002-18",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue/Navy",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Olive",
    itemNumber: "720002-19",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Artichoke",
    itemNumber: "720002-20",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Lime",
    itemNumber: "720002-21",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Grass",
    itemNumber: "720002-22",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Peacock",
    itemNumber: "720002-23",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue/Green",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Pepper",
    itemNumber: "720002-24",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Grey/Brown",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Forest",
    itemNumber: "720002-25",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Red",
    itemNumber: "720002-26",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Red",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Barn",
    itemNumber: "720002-27",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Red",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Beach",
    itemNumber: "720002-28",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Cream",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Beige",
    itemNumber: "720002-29",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Beige/Cream",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Cocoa",
    itemNumber: "720002-30",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Nut",
    itemNumber: "720002-31",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Ciel",
    itemNumber: "720002-32",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Bark",
    itemNumber: "720002-33",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Desert",
    itemNumber: "720002-37",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Tan",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Mulberry",
    itemNumber: "720002-38",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Purple",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Sea Foam",
    itemNumber: "720002-40",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Pistachio",
    itemNumber: "720002-41",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Sea Grass",
    itemNumber: "720002-44",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Green/Natural",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Cinnamon",
    itemNumber: "720002-45",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Rosé",
    itemNumber: "720002-46",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Pink",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Fuschia",
    itemNumber: "720002-47",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Pink/Purple",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Lipstick",
    itemNumber: "720002-48",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Pink/Red",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Caribe",
    itemNumber: "720002-51",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Green/Blue",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Antique",
    itemNumber: "720002-52",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Gold/Yellow",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Tangerine",
    itemNumber: "720002-53",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Orange",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Berry",
    itemNumber: "720002-54",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Purple",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Aubergine",
    itemNumber: "720002-56",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Purple",
  },
  {
    fabric: "Brushed Cotton Linen",
    colorway: "Dijon",
    itemNumber: "720002-57",
    price: 77,
    content: "63% Cotton 37% Linen",
    width: '54"',
    description: "Solid",
    color: "Gold/Yellow",
  },
  {
    fabric: "Linen",
    colorway: "Grey",
    itemNumber: "720004-01",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Linen",
    colorway: "Royal",
    itemNumber: "720004-02",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue/Navy",
  },
  {
    fabric: "Linen",
    colorway: "Teal",
    itemNumber: "720004-03",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Linen",
    colorway: "Cadet",
    itemNumber: "720004-04",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Linen",
    colorway: "Slate",
    itemNumber: "720004-05",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Linen",
    colorway: "Celadon",
    itemNumber: "720004-06",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Grey/Green",
  },
  {
    fabric: "Linen",
    colorway: "Pink",
    itemNumber: "720004-07",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Pink",
  },
  {
    fabric: "Linen",
    colorway: "Rust",
    itemNumber: "720004-08",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Red/Orange",
  },
  {
    fabric: "Linen",
    colorway: "Brown",
    itemNumber: "720004-09",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Linen",
    colorway: "Pale Grey",
    itemNumber: "720004-10",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Linen",
    colorway: "Cloud",
    itemNumber: "720004-11",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Grey/Off White",
  },
  {
    fabric: "Linen",
    colorway: "Light Taupe",
    itemNumber: "720004-12",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Natural/Tan",
  },
  {
    fabric: "Linen",
    colorway: "Greggio",
    itemNumber: "720004-13",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Natural",
  },
  {
    fabric: "Linen",
    colorway: "Bisque",
    itemNumber: "720004-14",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Natural",
  },
  {
    fabric: "Linen",
    colorway: "Off White",
    itemNumber: "720004-15",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Off White",
  },
  {
    fabric: "Linen",
    colorway: "White",
    itemNumber: "720004-16",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "White",
  },
  {
    fabric: "Linen",
    colorway: "Turquoise",
    itemNumber: "720004-17",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue/Green",
  },
  {
    fabric: "Linen",
    colorway: "Pebble",
    itemNumber: "720004-18",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Tan/Brown/Natural",
  },
  {
    fabric: "Linen",
    colorway: "Taupe",
    itemNumber: "720004-19",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Tan/Brown/Natural",
  },
  {
    fabric: "Linen",
    colorway: "Moutarde",
    itemNumber: "720004-20",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Gold/Yellow",
  },
  {
    fabric: "Linen",
    colorway: "Manatee",
    itemNumber: "720004-21",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Grey",
  },
  {
    fabric: "Linen",
    colorway: "Noire",
    itemNumber: "720004-22",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Black/Grey",
  },
  {
    fabric: "Linen",
    colorway: "Ciel",
    itemNumber: "720004-24",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Blue",
  },
  {
    fabric: "Linen",
    colorway: "Cranberry",
    itemNumber: "720004-25",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Red",
  },
  {
    fabric: "Linen",
    colorway: "Peat",
    itemNumber: "720004-26",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Brown",
  },
  {
    fabric: "Linen",
    colorway: "Hemp",
    itemNumber: "720004-27",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Linen",
    colorway: "Basil",
    itemNumber: "720004-28",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Green",
  },
  {
    fabric: "Linen",
    colorway: "Straw",
    itemNumber: "720004-29",
    price: 126,
    content: "100% Linen",
    width: '54"',
    description: "Solid",
    color: "Tan/Beige",
  },
]

// Material keywords to match
const materialKeywords = ["Cotton", "Linen", "Wool"]

async function run() {
  console.log("Fetching existing colors and materials from Sanity...")

  // Fetch existing colors and materials
  const [colors, materials] = await Promise.all([
    client.fetch(`*[_type == "color"] { _id, name, "slug": slug.current }`),
    client.fetch(`*[_type == "material"] { _id, name, "slug": slug.current }`),
  ])

  console.log(`Found ${colors.length} colors and ${materials.length} materials`)

  // Create lookup maps
  const colorMap = new Map<string, string>()
  colors.forEach((c: any) => {
    colorMap.set(c.name.toLowerCase(), c._id)
    colorMap.set(c.slug.toLowerCase(), c._id)
  })

  const materialMap = new Map<string, string>()
  materials.forEach((m: any) => {
    materialMap.set(m.name.toLowerCase(), m._id)
    materialMap.set(m.slug.toLowerCase(), m._id)
  })

  console.log(`\nProcessing ${openStockData.length} Open Stock items...`)

  let successCount = 0
  let errorCount = 0

  for (const item of openStockData) {
    try {
      // Find color references
      const colorRefs: Array<{ _type: "reference"; _ref: string; _key: string }> = []
      const colorNames = item.color.split("/").map((c) => c.trim().toLowerCase())

      for (const colorName of colorNames) {
        const colorId = colorMap.get(colorName)
        if (colorId) {
          colorRefs.push({
            _type: "reference",
            _ref: colorId,
            _key: `color-${colorId}`,
          })
        } else {
          console.warn(`  Warning: Color "${colorName}" not found for item ${item.itemNumber}`)
        }
      }

      // Find material references from content field
      const materialRefs: Array<{ _type: "reference"; _ref: string; _key: string }> = []
      const contentLower = item.content.toLowerCase()

      for (const keyword of materialKeywords) {
        if (contentLower.includes(keyword.toLowerCase())) {
          const materialId = materialMap.get(keyword.toLowerCase())
          if (materialId) {
            materialRefs.push({
              _type: "reference",
              _ref: materialId,
              _key: `material-${materialId}`,
            })
          }
        }
      }

      // Create the Open Stock item document
      const doc = {
        _type: "openStockItem",
        itemNumber: item.itemNumber,
        fabric: item.fabric,
        colorway: item.colorway,
        price: item.price,
        content: item.content,
        width: item.width,
        description: item.description,
        colors: colorRefs.length > 0 ? colorRefs : undefined,
        materials: materialRefs.length > 0 ? materialRefs : undefined,
      }

      await client.create(doc)
      console.log(`  Created: ${item.itemNumber} - ${item.fabric} (${item.colorway})`)
      successCount++
    } catch (error) {
      console.error(`  Error creating ${item.itemNumber}:`, error)
      errorCount++
    }
  }

  console.log(`\n--- Migration Complete ---`)
  console.log(`Successfully created: ${successCount}`)
  console.log(`Errors: ${errorCount}`)
}

run().catch(console.error)
